{ Error: Internal Server Error
    at Request.callback (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:706:15)
    at IncomingMessage.parser (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 500,
  response:
   Response {
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Socket],
        _consuming: true,
        _dumped: false,
        req: [ClientRequest],
        text: '500 Internal Server Error\n\nServer got itself in trouble' },
     request:
      Request {
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'POST',
        url: 'http://127.0.0.1:8081/',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        _query: [],
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        _data: [Object],
        req: [ClientRequest],
        protocol: 'http:',
        host: '127.0.0.1:8081',
        _endCalled: true,
        _callback: [Function],
        res: [IncomingMessage],
        response: [Circular],
        called: true },
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 11161,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST / HTTP/1.1\r\nhost: smee.io\r\nAccept-Encoding: gzip, deflate\r\nuser-agent: GitHub-Hookshot/bc38b7a\r\ncontent-type: application/json\r\nconnection: close\r\naccept: */*\r\nx-github-delivery: 93691d00-d097-11ea-9bc2-9ad5469055de\r\nx-github-event: check_run\r\nx-hub-signature: sha1=897f23d6122a800b924fbfea3cc3db1cc581bb16\r\nx-request-id: aa70d767-97d7-48ed-9543-6784e9de8e08\r\nx-forwarded-for: 140.82.115.247\r\nx-forwarded-proto: https\r\nx-forwarded-port: 443\r\nvia: 1.1 vegur\r\nconnect-time: 1\r\nx-request-start: 1595916002441\r\ntotal-route-time: 0\r\ncontent-length: 11161\r\ntimestamp: 1595916002445\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     text: '500 Internal Server Error\n\nServer got itself in trouble',
     body: {},
     files: undefined,
     buffered: true,
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '55',
        date: 'Tue, 28 Jul 2020 06:00:06 GMT',
        server: 'Python/3.8 aiohttp/3.6.2',
        connection: 'close' },
     header:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '55',
        date: 'Tue, 28 Jul 2020 06:00:06 GMT',
        server: 'Python/3.8 aiohttp/3.6.2',
        connection: 'close' },
     statusCode: 500,
     status: 500,
     statusType: 5,
     info: false,
     ok: false,
     redirect: false,
     clientError: false,
     serverError: true,
     error:
      { Error: cannot POST / (500)
          at Response.toError (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/response.js:94:15)
          at ResponseBase._setStatusProperties (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/response-base.js:123:16)
          at new Response (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/response.js:41:8)
          at Request._emitResponse (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:752:20)
          at IncomingMessage.parser (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:916:38)
          at IncomingMessage.emit (events.js:187:15)
          at endReadableNT (_stream_readable.js:1094:12)
          at process._tickCallback (internal/process/next_tick.js:63:19)
        status: 500,
        text: '500 Internal Server Error\n\nServer got itself in trouble',
        method: 'POST',
        path: '/' },
     created: false,
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     unprocessableEntity: false,
     type: 'text/plain',
     charset: 'utf-8',
     links: {},
     setEncoding: [Function: bound ],
     redirects: [] } }
{ Error: Internal Server Error
    at Request.callback (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:706:15)
    at IncomingMessage.parser (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 500,
  response:
   Response {
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Socket],
        _consuming: true,
        _dumped: false,
        req: [ClientRequest],
        text: '500 Internal Server Error\n\nServer got itself in trouble' },
     request:
      Request {
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'POST',
        url: 'http://127.0.0.1:8081/',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        _query: [],
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        _data: [Object],
        req: [ClientRequest],
        protocol: 'http:',
        host: '127.0.0.1:8081',
        _endCalled: true,
        _callback: [Function],
        res: [IncomingMessage],
        response: [Circular],
        called: true },
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 10755,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST / HTTP/1.1\r\nhost: smee.io\r\nAccept-Encoding: gzip, deflate\r\nuser-agent: GitHub-Hookshot/bc38b7a\r\ncontent-type: application/json\r\nconnection: close\r\naccept: */*\r\nx-github-delivery: c7483732-d097-11ea-8214-3bb0c248c7bf\r\nx-github-event: status\r\nx-hub-signature: sha1=9f8be58de5da2aeee7147c9b1bdca93577cf9af1\r\nx-request-id: 9bdff1f8-e2dd-41ca-9bde-ca094402d615\r\nx-forwarded-for: 140.82.115.150\r\nx-forwarded-proto: https\r\nx-forwarded-port: 443\r\nvia: 1.1 vegur\r\nconnect-time: 1\r\nx-request-start: 1595916089416\r\ntotal-route-time: 0\r\ncontent-length: 10755\r\ntimestamp: 1595916089421\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     text: '500 Internal Server Error\n\nServer got itself in trouble',
     body: {},
     files: undefined,
     buffered: true,
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '55',
        date: 'Tue, 28 Jul 2020 06:01:37 GMT',
        server: 'Python/3.8 aiohttp/3.6.2',
        connection: 'close' },
     header:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '55',
        date: 'Tue, 28 Jul 2020 06:01:37 GMT',
        server: 'Python/3.8 aiohttp/3.6.2',
        connection: 'close' },
     statusCode: 500,
     status: 500,
     statusType: 5,
     info: false,
     ok: false,
     redirect: false,
     clientError: false,
     serverError: true,
     error:
      { Error: cannot POST / (500)
          at Response.toError (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/response.js:94:15)
          at ResponseBase._setStatusProperties (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/response-base.js:123:16)
          at new Response (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/response.js:41:8)
          at Request._emitResponse (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:752:20)
          at IncomingMessage.parser (/home/zhangchunle/anaconda2/envs/bot/lib/node_modules/smee-client/node_modules/superagent/lib/node/index.js:916:38)
          at IncomingMessage.emit (events.js:187:15)
          at endReadableNT (_stream_readable.js:1094:12)
          at process._tickCallback (internal/process/next_tick.js:63:19)
        status: 500,
        text: '500 Internal Server Error\n\nServer got itself in trouble',
        method: 'POST',
        path: '/' },
     created: false,
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     unprocessableEntity: false,
     type: 'text/plain',
     charset: 'utf-8',
     links: {},
     setEncoding: [Function: bound ],
     redirects: [] } }
{ Error: socket hang up
    at createHangUpError (_http_client.js:322:15)
    at Socket.socketOnEnd (_http_client.js:425:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET', response: undefined }
{ Error: connect ECONNREFUSED 127.0.0.1:8081
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8081,
  response: undefined }
{ Error: connect ECONNREFUSED 127.0.0.1:8081
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8081,
  response: undefined }
{ Error: connect ECONNREFUSED 127.0.0.1:8081
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8081,
  response: undefined }
